### ISSUE TITLE
setImmediate and process.nextTick not working

### ISSUE THREAD

**Issue by PhakornKiong** [Hopding/js-visualizer-9000-server#7]
First of all, great works on the visualizer!
I've tried setImmediate and process.nextTick, but once I went over the code, seems like there isn't any support for it (correct me if I'm wrong).

May I know if there are going to be any support for setImmediate or process.nextTick in the future?

**Comment by Hopding** [comment]
Hello @Darkripper214!

`setImmediate` and `process.nextTick` are not standard JS APIs. They are node specific. So I do not currently have plans to add support for them. However, if you (or anybody else) is interested in creating a PR to add support (similar to https://github.com/Hopding/js-visualizer-9000-server/pull/3), I would be open to merging it.

**Comment by PhakornKiong** [comment]
> Hello @Darkripper214!
> 
> `setImmediate` and `process.nextTick` are not standard JS APIs. They are node specific. So I do not currently have plans to add support for them. However, if you (or anybody else) is interested in creating a PR to add support (similar to #3), I would be open to merging it.


Ok cool, I might be doing a similar project to yours but focusing more on nodeJS side.

Btw I noted that you're using `falafel` to instruments function. I've done some work using babel transform instead, would you be open to merging the change? I will open a PR if you're open to merging.
